## Configuration File for the Forecast of a Qantile Random Forest (QRF) Model ##

# Set the path and file names of the input data 
PATH_input_data_era5 : './Data_in_csv_Format/'
ifile_input_data_era5 : 'era5_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_60W_60E_20N_80N_1950_2020_lead_time_14d.csv'

PATH_input_data_s2s : './Data_in_csv_Format/'
ifile_input_data_s2s : 's2s_reforecasts_statistics_ensemble_info_u10_z100_z300_z500_z850_t850_H850_u300_msl_t2m_60W_60E_20N_80N_2000_2020_lead_time_14d.csv'

# Set the path to the model
PATH_model : './Trained_QRF_Models/'

# Set the names of the models to be used
list_file_name_model: [
'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2000_2001.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2001_2002.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2002_2003.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2003_2004.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2004_2005.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2005_2006.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2006_2007.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2007_2008.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2008_2009.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2009_2010.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2010_2011.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2011_2012.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2012_2013.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2013_2014.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2014_2015.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2015_2016.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2016_2017.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2017_2018.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2018_2019.pt', 'QRF_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens_60W_60E_20N_80N_lead_14d_without_2019_2020.pt']

# Set the path to the desired output folder
PATH_predictions : './Predictions_QRF_Models/'

# Decide whether reanalysis data should be included in the predictors
use_reanalysis_data : True

# Set the quantiles of the quantile random forest (for evenly distributed quantiles the number of quantiles is sufficient)
number_of_quantiles : 100
distributed_evenly : True
list_quantiles_qrf : [0.01, 0.05, 0.10, 0.20, 0.25, 0.33, 0.50, 0.66, 0.75, 0.95, 0.99]

# Set additional information for the model name which cannot be inferred from the data directly (keep it short but still informative)
input_data : 'month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens'
ground_truth : 'av_tg'
unit_of_ground_truth_and_prediction : 'K'
location_input: '60W_60E_20N_80N'
location_ground_truth: '3E_20E_45N_60N'

# Set the lead time of the forecast
lead_time : 14

# Set the details to the desired winters
start_year_of_first_winter : 2000
start_year_of_last_winter : 2019

start_month_winter : 11
start_day_winter: 1

end_month_winter: 4
end_day_winter: 30






