## Configuration File for Creating and Training a Quantile Random Forest (QRF) Model ##

# Set the path and file names of the input data (only needed if reanalysis data should be included in the predictors)
PATH_input_data_era5 : './Data_in_csv_Format/'
ifile_input_data_era5 : 'era5_pca_n10_u10_z100_z250_z500_z850_t850_H850_u300_msl_60W_60E_20N_80N_1950_2020_lead_time_14d.csv'

PATH_input_data_s2s : './Data_in_csv_Format/'
ifile_input_data_s2s : 's2s_reforecasts_pca_n10_ensemble_info_u10_z100_z300_z500_z850_t850_H850_u300_msl_t2m_60W_60E_20N_80N_2000_2020_lead_time_14d.csv'

# Set the path and file names of the ground truth
PATH_ground_truth : './Data_in_csv_Format/'
ifile_ground_truth : 'eobsv23e_tg_3E_20E_45N_60N_1950_2020_only_Nov_Apr_14d_lead.csv'

# Set the path to the desired output folder for the trained model and its 'metadata-file'
PATH_model : './Trained_QRF_Models/'

# Set the path to the folder for the plot of the feature importance (only needed if a feature importance is performed)
PATH_plots : './Plots/'

# Decide whether reanalysis data should be included in the predictors
use_reanalysis_data : True

# Set additional information for the model name which cannot be inferred from the data directly (keep it short but still informative)
short_model_name : 'QRF_stat_all_s2s_ens_era5'
input_data : 'month_pca_n10_u10_z100_z250_z500_z850_t850_H850_u300_msl_1000_trees_min_node_size_5_s2s_era5_ens'
ground_truth : 'av_tg'
location_input: '60W_60E_20N_80N'
location_ground_truth: '3E_20E_45N_60N'

# Set additional information for the model's 'metadata-file' (these can be longer)
dataset_input_data : 's2s_reforecasts'
dataset_ground_truth : 'eobs_v23_1e'
type_input_data : 'PCA_of_field'
type_ground_truth : 'average_of_field'
unit_of_ground_truth_and_prediction : 'K'
training_period : 'winters_1950_2020'
training_type : 'crossvalidation'

# Decide if you want to save detailed information of the individual trees for e.g. applying Shapley Additive Explanations later (this will make the training notably slower)
obtain_additional_details_of_trees : False

# Set the lead time of the model (in days)
lead_time : 14
# Set the details of the desired winters for validation (the winter to be predicted is left out during training -> leave-one-(winter)-out-cross validation)
start_year_of_first_winter : 2000
start_year_of_last_winter : 2019

start_month_winter : 11
start_day_winter: 1

end_month_winter: 4
end_day_winter: 30

